version: "2"
services:
    server:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - database
        volumes:
            - maven-cache:/root/.m2
            - .:/work
        working_dir: "/work"
        command: "/bin/bash/"
volumes:
    maven-cache: {}
